name: traffic_light_classifier
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - bleach==1.5.0
  - boto3==1.4.7
  - botocore==1.7.7
  - cycler==0.10.0
  - docutils==0.14
  - h5py==2.7.1
  - html5lib==0.9999999
  - jmespath==0.9.3
  - keras==2.0.8
  - markdown==2.6.9
  - matplotlib==2.0.2
  - numpy==1.13.1
  - olefile==0.44
  - opencv-python==3.3.0.10
  - pickleshare==0.7.4
  - pillow==4.2.1
  - protobuf==3.4.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pyyaml==3.12
  - s3transfer==0.1.11
  - scikit-learn==0.19.0
  - scipy==0.19.1
  - six==1.10.0
